all:
	coqc Util.v -Q . HYDLA
	coqc Partial.v -Q . HYDLA
	coqc Trajectory.v -Q . HYDLA
	coqc PropFormula.v -Q . HYDLA
	coqc BouncingParticle.v -Q . HYDLA
	coqc ParameterizedBouncingParticle.v -Q . HYDLA
